// @generated by circuits/build/gen-oracle-fixture.mjs — deterministic Ed25519 reserve-oracle fixture (crisp v2)
pub const ORACLE_PUBKEY: &str = "a39b3268c360e9f92863855ff443c22a8fe57502729ab3dbba0264f0b0565d3a";
pub const ORACLE_SIG: &str = "77af7a74a73046696dccfa8d46be6f5a51d27d6be2a0b07f941e35b181f938797093d80d8f96c4308b1493e501e18ed6737efef2b60dda3f1138009bf9c1ad0f";
pub const ORACLE_RESERVES: u128 = 41665;
pub const ORACLE_KYC_ROOT: &str = "0ecdfe0997c23a0fe261aca9555027ffd450f0b45e3c17631ae3243c213d7cd1";
